name: Demo pages deploy CI
on:
  push:
    branches: ["dev"]

permissions: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Build cinny client
        run: npm ci && npm run build
      
      - name: Debug echo
        run: cat dist/public/element-call/index.html

      - name: Upload artifact
        run: npx wrangler deploy
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}